import { IProduct, TFilter } from "./types";
import donut from "../assets/donut.png";
import croissant from "../assets/croissant.png";
import cake from "../assets/cake.png";

export const TELEGRAM = window.Telegram.WebApp;

export const PRODUCTS: IProduct[] = [
  {
    id: 0,
    name: "Pink Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Sugar, flour, butter, strawberry jam, pink glaze",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.5,
    rate: 5,
  },
  {
    id: 1,
    name: "White Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Sugar, flour, butter, white glaze",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 5.5,
    rate: 5,
  },
  {
    id: 2,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Sugar, flour, butter, chocolate topping",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 3,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 4,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 5,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 6,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 7,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 8,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 9,
    name: "Choco Donut",
    type: "donut",
    img: donut,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Donut composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 4.0,
    rate: 5,
  },
  {
    id: 10,
    name: "Choco Croissant",
    type: "croissant",
    img: croissant,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Choco Croissant composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 2.0,
    rate: 5,
  },
  {
    id: 11,
    name: "Vanila Croissant",
    type: "croissant",
    img: croissant,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Vanila Croissant composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 2.0,
    rate: 5,
  },
  {
    id: 12,
    name: "Vanila Croissant",
    type: "croissant",
    img: croissant,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Vanila Croissant composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 2.0,
    rate: 5,
  },
  {
    id: 13,
    name: "Vanila Croissant",
    type: "croissant",
    img: croissant,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Vanila Croissant composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 2.0,
    rate: 5,
  },
  {
    id: 14,
    name: "Vanila Croissant",
    type: "croissant",
    img: croissant,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Vanila Croissant composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 2.0,
    rate: 5,
  },
  {
    id: 14,
    name: "Vanila Croissant",
    type: "croissant",
    img: croissant,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Vanila Croissant composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 2.0,
    rate: 5,
  },
  {
    id: 16,
    name: "Cheesecake",
    type: "cake",
    img: cake,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Cheesecake composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.0,
    rate: 5,
  },
  {
    id: 17,
    name: "Cheesecake",
    type: "cake",
    img: cake,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Cheesecake composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.0,
    rate: 5,
  },
  {
    id: 18,
    name: "Cheesecake",
    type: "cake",
    img: cake,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Cheesecake composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.0,
    rate: 5,
  },
  {
    id: 19,
    name: "Cheesecake",
    type: "cake",
    img: cake,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Cheesecake composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.0,
    rate: 5,
  },
  {
    id: 20,
    name: "Cheesecake",
    type: "cake",
    img: cake,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Cheesecake composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.0,
    rate: 5,
  },
  {
    id: 21,
    name: "Cheesecake",
    type: "cake",
    img: cake,
    description:
      "The sweet and juicy combo of pink glaze and strawberry jam, introduce withe the Pink Donut as soon as possible.",
    composition: "Cheesecake composition",
    energyValue: 550,
    cookingTime: { min: 5, max: 10 },
    price: 10.0,
    rate: 5,
  },
];
export const FILTERS: Set<TFilter> = new Set<TFilter>([
  "donut",
  "croissant",
  "cake",
  "all",
]);
